services:
  - type: web
    name: healthsync-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: your_mongo_atlas_connection_string
      - key: PORT
        value: 5000
